name: Path library

on:
  - push

jobs:
  build:
    name: Build rfpath library
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}